// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptpnbtsdqwiqlndytrnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0cG5idHNkcXdpcWxuZHl0cm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDk1NjMsImV4cCI6MjA1NzcyNTU2M30.kfmnes5FmmNe4U3b7_FuABQEij_8W7Fq5cgM9DQahMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);